apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels: 
    kubernetes.io/zone: poland
    kubernetes.io/region: eu
  annotations:
    changeNo: No12345
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

