apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: mk-test
  name: mk-test
spec:
  containers:
  - image: marcinkujawski/python-api:1.0
    name: mk-test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
