apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: registry.k8s.io/busybox:1.27.2
      command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: LXK_CM1
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: my-configmap
              # Specify the key associated with the value
              key: config.json
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: version
      envFrom: 
        - configMapRef:
            name: from-env
  restartPolicy: Never
