apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
  labels:
    type: nfs
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.100
    path: "/var/nfs-share"
