apiVersion: v1
kind: Pod
metadata:
  name: init-container-pod
spec:
  containers:
  - command:
    - sh
    - -c
    - while true; do echo logs data >> /output/output.log; sleep 5; done
    image: busybox
    name: busybox1
  initContainers:
  - command:
    - sh
    - -c
    - sleep 30; echo delay done
    image: busybox
    name: delay
  - command:
    - sh
    - -c
    - sleep 10; echo delay2 done
    image: busybox
    name: delay2
