apiVersion: v1
kind: Pod
metadata:
  name: init-container-pod2
spec:
  containers:
  - name: web
    image: nginx:1.19.2
    volumeMounts:
    - name: sharedvol
      mountPath: /usr/share/nginx/html/
  initContainers:
  - name: prepare
    image: alpine:3.2
    command: ['sh', '-c', 'apk update; apk add git; mkdir /app-content; git clone -b config https://github.com/mariano-italiano/lx-k_Apr.git /app-content']
    volumeMounts:
    - name: sharedvol
      mountPath: /app-content 
  volumes:
  - name: sharedvol
    emptyDir: {}
